CREATE OR REPLACE TABLE nicanor.bd_controlcomercial.MAESTRO_EMPRESAS_CULTURA as

SELECT 
Periodo_OK AS PERIODO,
RutEmpresa,
RutEmpresa as RUT_EMPRESA,

-----------DATOS MAESTRO------------------
RUT_HOLDING,
RUT_FINAL,
RUT_HOLDING_ORIGINAL,
RUT_FINAL_ORIGINAL,
RAZON_SOCIAL,
FECHA_AFILIACION,
CASE WHEN RutEmpresa=RUT_HOLDING THEN 1 WHEN RUT_HOLDING IS NULL THEN 1 ELSE 0 END AS RUT_MATRIZ,
CATEGORIA,
SEGMENTO_EMPRESA,
CODIGO_SUC_EMPRESA,
SUCURSAL_EMPRESA,
Segmento_Ejecutivo as SEGMENTO_EJECUTIVO,
Ejecutivo_Empresa as EJECUTIVO_EMPRESA,
CODIGO_CARTERA,
Sucursal_Ejecutivo AS SUCURSAL_EJECUTIVO,
CODIGO_SUC_EJECUTIVO,
Agente as AGENTE,
ZONA_EJECUTIVO,
REGION_SUCURSAL_EJECUTIVO,
SUBLIDER AS LIDER_SEGMENTO,
ASESOR_SEGMENTO,
JEFE_ASESOR_SEGMENTO,
LIDER_GESTION_CANALES,

-----------GESTION MUNICIPAL-----------
AGRUPACION_MUNICIPAL,

--------GEORREFERENCIACION--------
REGION_EMPRESA_AJUSTADO as REGION_EMPRESA,
CIUDAD_EMPRESA,
COMUNA_EMPRESA,
DIRECCION_EMPRESA,

--------DATOS AFILI1--------------
N_Trabajadores AS N_TRABAJADORES_EMPRESA,
N_Trabajadores_Extranjeros AS N_TRAB_EXTRANJEROS,
Promedio_Renta AS PROMEDIO_RENTA_IMPONIBLE,

---------UAI------------------
SaldoCapitalVigente_UAI as SALDO_CAPITAL, 
CostoFugaVigente_UAI as COSTO_FUGA,

---------ROTACION----------
ROUND(Rotacion12M/100,4) as ROTACION_TRAB_12MESES,

---------LLMM----------
Convenio_SIL AS CONVENIO_SIL,

-----------DATOS SII---------------
Actividad_economica_SII_2021 AS ACTIVIDAD_ECONOMICA_SII_2021,
Subrubro_economico_SII_2021 AS SUBRUBRO_SII_2021,
Rubro_economico_SII_2021 AS RUBRO_SII_2021,
Rubro_Empresa as RUBRO_EMPRESA_RIESGO,

----------SEGMENTOS------------------
Segmento_Final_Empresa as SEGMENTO_EMPRESA_FINAL,
Segmento_Final_Empresa_Simple AS SEGMENTO_EMPRESA_FINAL_RESUMEN,

-----------DATOS MODELOS------------
quintil as QUINTIL,
Q1_Priorizado as Q1_PRIORIZADO,
ROUND(Propension_fuga_historico,4) as PROPENSION_FUGA_MENSUAL,
(CASE WHEN Propension_fuga_historico > 0.064 THEN 1 ELSE 0 END) AS MARCA_ALTA_PROPENSION_FUGA,
QUINTIL_PROPENSION_FUGA,
ROUND(PORC_LEJANOS,4) as PORCENTAJE_AFILIADOS_LEJANOS,
PROXIMIDAD AS MATRIZ_PROXIMIDAD_TRABAJADORES_CLA,
RIESGO AS RIESGO_VOTACION_EMPRESAS,

---------DATOS CREDITO--------------
cast(MOV_MONTO as int) AS MONTO_COBRADO_PLANILLA_CREDITO,
cast(MONTO_PAGADO  as int) AS MONTO_PAGADO_PLANILLA_CREDITO,
cast(MOV_MONTO_DEPURADO  as int) AS MONTO_COBRADO_DEPURADO_PLANILLA_CREDITO,
cast(MONTO_PAGADO_DEPURADO as int) AS MONTO_PAGADO_DEPURADO_PLANILLA_CREDITO,
Marca_Bloqueo_Empresas AS MARCA_BLOQUEO_CREDITO,
Motivo_Bloqueo as MOTIVO_BLOQUEO_CREDITO,
Tipo_Bloqueo AS TIPO_BLOQUEO_CREDITO,

------SATISFACCION----------
N_Encuestas AS N_ENCUESTAS_EPA,
Minima_Satisfaccion_Ejecutivo as MIN_SATISFACCION_EJECUTIVO_EPA,
ROUND(Promedio_Satisfaccion_Ejecutivo,4) as AVG_SATISFACCION_EJECUTIVO_EPA,
Minima_Recomendacion_CLA AS MIN_RECOMENDACION_CLA_EPA,
ROUND(Promedio_Recomendacion_CLA,4) as AVG_RECOMENDACION_CLA_EPA,
N_Negaciones_Visita AS N_NEGACIONES_VISITAS,

-----COBERTURA---------------
N_Visitas as N_VISITAS_COBERTURA,
N_Visitas_Presenciales AS N_COBERTURA_PRESENCIALES,
N_Visitas_Stand AS N_COBERTURA_STAND,
N_Visitas_Video_Llamada AS N_COBERTURA_VIDEO,

-------ESTADO VIGILANCIA---------
Estado_Vigilancia as ESTADO_VIGILANCIA,

----SCANNER360--------------
round(Penetracion_CLA,4) as PENETRACION_CLA,

--BBSS--
round(Uso_bbss,4) as PENETRACION_BBSS,
cumplimiento_bbss as CUMPLIMIENTO_PENETRACION_BBSS,
N_Beneficios_Usados AS N_BENEFICIOS_USADOS,
RU_Usador_Beneficio_No_Masivo AS RU_USO_BENEFICIO_NO_MASIVO,

--PPFF--
round(Uso_ppff,4) as STOCK_PPFF,
cumplimiento_ppff as CUMPLIMIENTO_STOCK_PPFF,

--CANALES--
round(Uso_Canales_Digitales,4) as PENETRACION_CANALES_DIGITALES,
cumplimiento_uso_canales_digitales as CUMPLIMIENTO_PENETRACION_CANALES_DIGITALES,
N_Trab_con_Clave_Virtual AS N_TRAB_CLAVE_VIRTUAL,
N_Visitas_canales_digitales AS N_VISITAS_CANAL_DIGITAL,
RU_Visita_canales_digitales AS RU_VISITAS_CANAL_DIGITAL,
N_Visitas_Sucursal AS N_VISITAS_SUCURSAL,
RU_Visita_Sucursal AS RU_VISITAS_SUCURSAL,

--MCR--
round(MCR_Firmados,4) as STOCK_MCR,
cumplimiento_stock_MCR AS CUMPLIMIENTO_STOCK_MCR,

--MOROSIDAD--
round(PORC_MORA,4) as MOROSIDAD_EMPRESA,
CUMPLIMIENTO_MORA_EMPRESA AS CUMPLIMIENTO_MOROSIDAD_EMPRESA,     
N_PERSONAS_MOROSAS,
round(PORC_REGULARIZA,4) as MOROSOS_CON_OFERTA_REGULARIZACION,

--RECLAMOS--
N_RECLAMOS,
round(PORC_RECLAMOS_TODOS,4) as INDICADOR_MENSUAL_N_RECLAMOS,

--MESA DE SERVICIO EMPRESA--
N_REQUERIMIENTOS_MSE,
N_REQUERIMIENTOS_EN_PUNTA_MSE,

-------DATOS RUT FINAL-------------
RAZON_SOCIAL_RUT_FINAL,
N_EMPRESAS_RUT_FINAL,
N_TRABAJADORES_RUT_FINAL,
Ejecutivo_Empresa_RUT_FINAL AS EJECUTIVO_EMPRESA_RUT_FINAL,
Rubro_Empresa_RUT_FINAL AS RUBRO_EMPRESA_RIESGO_RUT_FINAL,
REGION_EMPRESA_AJUSTADO_RUT_FINAL AS REGION_EMPRESA_RUT_FINAL,
round(Uso_bbss_Rut_Final,4) as PENETRACION_BBSS_RUT_FINAL,
cumplimiento_bbss_Rut_Final as CUMPLIMIENTO_PENETRACION_BBSS_RUT_FINAL,
round(Uso_ppff_Rut_Final,4) as STOCK_PPFF_RUT_FINAL,
cumplimiento_ppff_Rut_Final AS CUMPLIMIENTO_STOCK_PPFF_RUT_FINAL,


FROM `nicanor.bd_controlcomercial.CONSOLIDADO_EMPRESAS_MAESTRO_PANEL2` 
where Periodo_OK is not null

union all 

select *
from `nicanor.bd_controlcomercial.MAESTRO_EMPRESAS_CULTURA_ACTUAL`