--DECLARACION DE VARIABLES RESPECTO A LOS PUNTAJES INDICADOS EN PLANILLA GOOGLE

--EEVV
DECLARE PUNTAJE_EEVV_RIESGO_FUGA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Riesgo de fuga');
DECLARE PUNTAJE_EEVV_CONTENCION_ACTIVA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Contención activa');
DECLARE PUNTAJE_EEVV_ALERTA_PREV INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Alerta preventiva');
DECLARE PUNTAJE_EEVV_POST_CONT INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Post-Contencion');

DECLARE MENSAJE_EEVV_RIESGO_FUGA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Riesgo de fuga');
DECLARE MENSAJE_EEVV_CONTENCION_ACTIVA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Contención activa');
DECLARE MENSAJE_EEVV_ALERTA_PREV STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Alerta preventiva');
DECLARE MENSAJE_EEVV_POST_CONT STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Estados de Vigilancia' AND VARIABLE = 'Post-Contencion');

--COBERTURA
DECLARE PUNTAJE_0_COBERTURA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '0');
DECLARE PUNTAJE_1_COBERTURA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '1');
DECLARE PUNTAJE_2_COBERTURA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '2');

DECLARE MENSAJE_0_COBERTURA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '0');
DECLARE MENSAJE_1_COBERTURA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '1');
DECLARE MENSAJE_2_COBERTURA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Cobertura' AND VARIABLE = '2');

--BLOQUEO EMPRESA
DECLARE PUNTAJE_BLOQUEO_PLANILLA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Mora Planilla');
DECLARE PUNTAJE_BLOQUEO_ADMISION INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Área Admisión');
DECLARE PUNTAJE_BLOQUEO_LEY INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Ley Insolvencia');

DECLARE MENSAJE_BLOQUEO_PLANILLA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Mora Planilla');
DECLARE MENSAJE_BLOQUEO_ADMISION STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Área Admisión');
DECLARE MENSAJE_BLOQUEO_LEY STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Bloqueo Empresa' AND VARIABLE = 'Ley Insolvencia');

--AFILIADOS LEJANOS
DECLARE PUNTAJE_LEJANOS_80_POR INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Mayor a 0,8');
DECLARE PUNTAJE_LEJANOS_70_POR INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Entre 0,7 y 0,8');
DECLARE PUNTAJE_LEJANOS_50_POR INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Entre 0,5  y 0,69');

DECLARE MENSAJE_LEJANOS_80_POR STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Mayor a 0,8');
DECLARE MENSAJE_LEJANOS_60_POR STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Entre 0,6 y 0,8');
DECLARE MENSAJE_LEJANOS_50_POR STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Porcentaje Lejanos' AND VARIABLE = 'Entre 0,5  y 0,59');

--RECOMENDACION EPA
DECLARE PUNTAJE_NPS_EPA_4 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = 'Menor o igual a 4');
DECLARE PUNTAJE_NPS_EPA_5 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = '5');
DECLARE PUNTAJE_NPS_EPA_6 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = 'Entre 6 y 8');

DECLARE MENSAJE_NPS_EPA_4 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = 'Menor o igual a 4');
DECLARE MENSAJE_NPS_EPA_5 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = '5');
DECLARE MENSAJE_NPS_EPA_6 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Recomendación EPA' AND VARIABLE = 'Entre 6 y 8');

--SATISFACCION EPA
DECLARE PUNTAJE_SNEX_EPA_3 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = 'Menor o igual a 3');
DECLARE PUNTAJE_SNEX_EPA_4 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = '4');
DECLARE PUNTAJE_SNEX_EPA_5 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = '5');

DECLARE MENSAJE_SNEX_EPA_3 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = 'Menor o igual a 3');
DECLARE MENSAJE_SNEX_EPA_4 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = '4');
DECLARE MENSAJE_SNEX_EPA_5 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Satisfacción EPA' AND VARIABLE = '5');

--N° CONTACTOS
DECLARE PUNTAJE_CONTACTOS_1_1 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '1 contacto 1 visita');
DECLARE PUNTAJE_CONTACTOS_1_MAS INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '1 contacto + 1 visita');
DECLARE PUNTAJE_CONTACTOS_2 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '2');

DECLARE MENSAJE_CONTACTOS_1_1 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '1 contacto 1 visita');
DECLARE MENSAJE_CONTACTOS_1_MAS STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '1 contacto + 1 visita');
DECLARE MENSAJE_CONTACTOS_2 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Contactos Cobertura' AND VARIABLE = '2');

--QUINTIL
DECLARE PUNTAJE_QUINTIL_PRIORIZADO_SIN_VISITA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = 'Priorizada sin Visita');
DECLARE PUNTAJE_QUINTIL_PRIORIZADO_VISITADA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = 'Priorizada con Visita');
DECLARE PUNTAJE_QUINTIL_1 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = '1');
DECLARE PUNTAJE_QUINTIL_2 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = '2');

DECLARE MENSAJE_QUINTIL_PRIORIZADO_SIN_VISITA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = 'Priorizada sin Visita');
DECLARE MENSAJE_QUINTIL_PRIORIZADO_VISITADA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = 'Priorizada con Visita');
DECLARE MENSAJE_QUINTIL_1 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = '1');
DECLARE MENSAJE_QUINTIL_2 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil' AND VARIABLE = '2');

--PROPENSION FUGA
DECLARE PUNTAJE_MODELO_FUGA_ALERTA INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil Propension Fuga' AND VARIABLE = 'Alta');
DECLARE PUNTAJE_MODELO_FUGA_Q1 INT64 DEFAULT (SELECT CAST(PUNTAJE AS INT) FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil Propension Fuga' AND VARIABLE = '1');

DECLARE MENSAJE_MODELO_FUGA_ALERTA STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil Propension Fuga' AND VARIABLE = 'Alta');
DECLARE MENSAJE_MODELO_FUGA_Q1 STRING DEFAULT (SELECT MENSAJE FROM TABLA_PLANILLA_ASIGNACION_PUNTAJES WHERE CATEGORIA = 'Quintil Propension Fuga' AND VARIABLE = '1');




CREATE OR REPLACE TABLE TABLA_SCANNER_EJECUTIVO as

-- SELECCION DE VARIABLES DESDE MAESTRO EMPRESAS QUE INTERVIENEN EN EL CALCULO O VISUALIZACION
with Datos_Maestro_Actual as (
SELECT RUTEMPRESA, 
RUT_HOLDING, 
RUT_FINAL,
RAZON_SOCIAL, 
RUBRO_EMPRESA_RIESGO, 
EJECUTIVO_EMPRESA, 
SUCURSAL_EJECUTIVO, 
LIDER_SEGMENTO, 
LIDER_GESTION_CANALES,
AGENTE, 
CASE WHEN Q1_Priorizado = 1 THEN 'Priorizada' ELSE CAST(QUINTIL AS STRING) END AS QUINTIL,
CASE WHEN MARCA_ALTA_PROPENSION_FUGA = 1 THEN "ALTA" ELSE CAST(QUINTIL_PROPENSION_FUGA AS STRING) END AS QUINTIL_PROPENSION,
ESTADO_VIGILANCIA,
TIPO_BLOQUEO_CREDITO,
PORCENTAJE_AFILIADOS_LEJANOS,
N_TRABAJADORES_EMPRESA,
N_TRABAJADORES_RUT_FINAL,
-----------------SCANNER 360-------------------------------
--BBSS--
PENETRACION_BBSS,
CUMPLIMIENTO_PENETRACION_BBSS,
--PPFF--
STOCK_PPFF,
STOCK_PPFF_SEGMENTO,
CUMPLIMIENTO_STOCK_PPFF,
--CANALES--
PENETRACION_CANALES_DIGITALES,
CUMPLIMIENTO_PENETRACION_CANALES_DIGITALES,
--MCR--
STOCK_MCR,
CUMPLIMIENTO_STOCK_MCR,
--MOROSIDAD--
MOROSIDAD_EMPRESA,
CUMPLIMIENTO_MOROSIDAD_EMPRESA,     
MOROSOS_CON_OFERTA_REGULARIZACION,
--RECLAMOS--
N_RECLAMOS,
INDICADOR_MENSUAL_N_RECLAMOS,
--MESA DE SERVICIO EMPRESA--
N_REQUERIMIENTOS_MSE,
N_REQUERIMIENTOS_EN_PUNTA_MSE,

FROM TABLA_MAESTRO_EMPRESAS
WHERE PERIODO IS NULL
AND EJECUTIVO_EMPRESA IS NOT NULL),


--Incorporacion de variables adicionales y especificas para los calculos
variables_totales as (
SELECT a.*,
b.N_DIAS_VISITADOS_Stand_ultimos_90_dias as N_VISITAS_STAND_PRESENCIAL_U3M, 
b.N_DIAS_VISITADOS_Presencial_ultimos_90_dias AS N_VISITAS_PRESENCIAL_U3M, 
IFNULL(b.N_DIAS_VISITADOS_ultimos_90_dias,0) AS N_VISITAS_TOTALES_U3M, 
IFNULL(b.N_CONTACTOS_ultimos_90_dias,0) AS N_CONTACTOS_U3M, 
b.Marca_Niega_Visita_xMeses,
b.PROMEDIO_SATISFACCION_xMeses,
b.PROMEDIO_RECOMENDACION_xMeses,
b.Fecha_Ultima_Visita,
b.Tipo_Actividad_Ultima_Visita,
b.Marca_Visita_Mes_Calendario,
b.correo_agente,
b.EMAIL_EJECUTIVO,
b.AGRUPACION_MUNICIPAL,
b.Q1_PRIORIZADO,
b.categoria,
case when b.sublider = 'Christian Gonzalez' then 'christian.gonzalez@cajalosandes.cl'
when b.sublider = 'Ximena Sahd' then 'ximena.sahd@cajalosandes.cl'
when b.sublider = 'Rigoberto Rojas' then 'rigoberto.rojas@cajalosandes.cl'
when b.sublider = 'Elisabeth Mossert' then 'elisabeth.mossert@cajalosandes.cl'
when b.sublider = 'Santiago Warnken' then 'santiago.warnken@cajalosandes.cl'
else "Revisar" end as Correo_Lider,		

FROM Datos_Maestro_Actual as a  
LEFT JOIN (SELECT *
FROM TABLA_MAESTRO_EMPRESAS_2
WHERE Periodo_OK = (SELECT MAX(PERIODO_OK) FROM TABLA_MAESTRO_EMPRESAS_2)) as b  
on a.RUTEMPRESA = b.RUTEMPRESA),


-- Calculo de puntaje y mensajes de motivos criticos de atencion
Puntaje_y_mensaje as (
select *,
--EEVV
CASE 
WHEN ESTADO_VIGILANCIA IN ('Desafiliación', 'Desestimada','Alerta No Validada', 'Empresa fuera de estado de vigilancia') THEN 0 
WHEN ESTADO_VIGILANCIA IS NULL THEN 0 
WHEN ESTADO_VIGILANCIA = 'Post-Contencion' THEN PUNTAJE_EEVV_POST_CONT
WHEN ESTADO_VIGILANCIA = 'Alerta preventiva' THEN PUNTAJE_EEVV_ALERTA_PREV
WHEN ESTADO_VIGILANCIA = 'Contención activa' THEN PUNTAJE_EEVV_CONTENCION_ACTIVA
WHEN ESTADO_VIGILANCIA = 'Riesgo de fuga' THEN PUNTAJE_EEVV_RIESGO_FUGA
ELSE 0 END AS PUNTAJE_EEVV,

CASE 
WHEN ESTADO_VIGILANCIA IN ('Desafiliación', 'Desestimada','Alerta No Validada', 'Empresa fuera de estado de vigilancia') THEN "" 
WHEN ESTADO_VIGILANCIA IS NULL THEN ""
WHEN ESTADO_VIGILANCIA = 'Post-Contencion' THEN MENSAJE_EEVV_POST_CONT
WHEN ESTADO_VIGILANCIA = 'Alerta preventiva' THEN MENSAJE_EEVV_ALERTA_PREV
WHEN ESTADO_VIGILANCIA = 'Contención activa' THEN MENSAJE_EEVV_CONTENCION_ACTIVA
WHEN ESTADO_VIGILANCIA = 'Riesgo de fuga' THEN MENSAJE_EEVV_RIESGO_FUGA
ELSE "" END AS MENSAJE_EEVV,

--COBERTURA
CASE
WHEN N_VISITAS_TOTALES_U3M = 0 THEN PUNTAJE_0_COBERTURA
WHEN N_VISITAS_TOTALES_U3M = 1 THEN PUNTAJE_1_COBERTURA
WHEN N_VISITAS_TOTALES_U3M = 2 THEN PUNTAJE_2_COBERTURA
ELSE 0 END AS PUNTAJE_COBERTURA_TOTAL_U3M,  

CASE
WHEN N_VISITAS_TOTALES_U3M = 0 THEN MENSAJE_0_COBERTURA
WHEN N_VISITAS_TOTALES_U3M = 1 THEN MENSAJE_1_COBERTURA
WHEN N_VISITAS_TOTALES_U3M = 2 THEN MENSAJE_2_COBERTURA
ELSE "" END AS MENSAJE_COBERTURA_TOTAL_U3M,  

--BLOQUEO
CASE
WHEN TIPO_BLOQUEO_CREDITO IS NULL THEN 0 
WHEN TIPO_BLOQUEO_CREDITO LIKE '%MORP%' THEN PUNTAJE_BLOQUEO_PLANILLA
WHEN TIPO_BLOQUEO_CREDITO LIKE '%ELDI%' THEN PUNTAJE_BLOQUEO_LEY 
WHEN TIPO_BLOQUEO_CREDITO LIKE '%ADME%' THEN PUNTAJE_BLOQUEO_ADMISION
ELSE 0 END AS PUNTAJE_BLOQUEO_EMPRESA,  

CASE
WHEN TIPO_BLOQUEO_CREDITO IS NULL THEN ""
WHEN TIPO_BLOQUEO_CREDITO LIKE '%MORP%' THEN MENSAJE_BLOQUEO_PLANILLA
WHEN TIPO_BLOQUEO_CREDITO LIKE '%ELDI%' THEN MENSAJE_BLOQUEO_LEY 
WHEN TIPO_BLOQUEO_CREDITO LIKE '%ADME%' THEN MENSAJE_BLOQUEO_ADMISION
ELSE "" END AS MENSAJE_BLOQUEO_EMPRESA,

--BLOQUEO
CASE
WHEN PORCENTAJE_AFILIADOS_LEJANOS <= 0.5 THEN 0 
WHEN PORCENTAJE_AFILIADOS_LEJANOS <= 0.7 THEN PUNTAJE_LEJANOS_50_POR 
WHEN PORCENTAJE_AFILIADOS_LEJANOS <= 0.8 THEN PUNTAJE_LEJANOS_70_POR 
WHEN PORCENTAJE_AFILIADOS_LEJANOS > 0.8 THEN PUNTAJE_LEJANOS_80_POR 
ELSE 0 END AS PUNTAJE_PORC_LEJANOS, 

CASE
WHEN PORCENTAJE_AFILIADOS_LEJANOS < 0.7 THEN "" 
WHEN PORCENTAJE_AFILIADOS_LEJANOS >= 0.7 THEN concat(round(PORCENTAJE_AFILIADOS_LEJANOS*100,0),"% Afiliados Lejanos a CLA") 
ELSE "" END AS MENSAJE_PORC_LEJANOS, 

--NPS
CASE
WHEN PROMEDIO_RECOMENDACION_xMeses < 4.1 THEN PUNTAJE_NPS_EPA_4
WHEN PROMEDIO_RECOMENDACION_xMeses < 5.5 THEN PUNTAJE_NPS_EPA_5
WHEN PROMEDIO_RECOMENDACION_xMeses <= 8 THEN PUNTAJE_NPS_EPA_6
ELSE 0 END AS PUNTAJE_EPA_RECOMENDACION, 

CASE
WHEN PROMEDIO_RECOMENDACION_xMeses < 4.1 THEN MENSAJE_NPS_EPA_4
WHEN PROMEDIO_RECOMENDACION_xMeses < 5.5 THEN MENSAJE_NPS_EPA_5
WHEN PROMEDIO_RECOMENDACION_xMeses <= 8 THEN MENSAJE_NPS_EPA_6
ELSE "" END AS MENSAJE_EPA_RECOMENDACION, 

--SNEX
CASE
WHEN PROMEDIO_SATISFACCION_xMeses <= 3 THEN PUNTAJE_SNEX_EPA_3
WHEN PROMEDIO_SATISFACCION_xMeses <= 4 THEN PUNTAJE_SNEX_EPA_4
WHEN PROMEDIO_SATISFACCION_xMeses <= 5 THEN PUNTAJE_SNEX_EPA_5  
ELSE 0 END AS PUNTAJE_EPA_SATISFACCION,

CASE
WHEN PROMEDIO_SATISFACCION_xMeses <= 3 THEN MENSAJE_SNEX_EPA_3
WHEN PROMEDIO_SATISFACCION_xMeses <= 4 THEN MENSAJE_SNEX_EPA_4
WHEN PROMEDIO_SATISFACCION_xMeses <= 5 THEN MENSAJE_SNEX_EPA_5  
ELSE "" END AS MENSAJE_EPA_SATISFACCION,  

--N° CONTACTOS
CASE
WHEN N_CONTACTOS_U3M = 1 and N_VISITAS_TOTALES_U3M = 1 THEN PUNTAJE_CONTACTOS_1_1 
WHEN N_CONTACTOS_U3M = 1 and N_VISITAS_TOTALES_U3M > 1 THEN PUNTAJE_CONTACTOS_1_MAS 
WHEN N_CONTACTOS_U3M = 2 THEN PUNTAJE_CONTACTOS_2
ELSE 0 END AS PUNTAJE_CANTIDAD_CONTACTOS,  

CASE
WHEN N_CONTACTOS_U3M = 1 and N_VISITAS_TOTALES_U3M = 1 THEN MENSAJE_CONTACTOS_1_1 
WHEN N_CONTACTOS_U3M = 1 and N_VISITAS_TOTALES_U3M > 1 THEN MENSAJE_CONTACTOS_1_MAS 
WHEN N_CONTACTOS_U3M = 2 THEN MENSAJE_CONTACTOS_2
ELSE "" END AS MENSAJE_CANTIDAD_CONTACTOS,  

--QUINTIL
CASE
WHEN QUINTIL = 'Priorizada' AND Marca_Visita_Mes_Calendario = 1 THEN PUNTAJE_QUINTIL_PRIORIZADO_VISITADA
WHEN QUINTIL = 'Priorizada' then PUNTAJE_QUINTIL_PRIORIZADO_SIN_VISITA
WHEN QUINTIL = '1' THEN PUNTAJE_QUINTIL_1
WHEN QUINTIL = '2' THEN PUNTAJE_QUINTIL_2 
ELSE 0 END AS PUNTAJE_QUINTIL,

CASE
WHEN QUINTIL = 'Priorizada' AND Marca_Visita_Mes_Calendario = 1 THEN MENSAJE_QUINTIL_PRIORIZADO_VISITADA
WHEN QUINTIL = 'Priorizada' then MENSAJE_QUINTIL_PRIORIZADO_SIN_VISITA
WHEN QUINTIL = '1' THEN MENSAJE_QUINTIL_1
WHEN QUINTIL = '2' THEN MENSAJE_QUINTIL_2 
ELSE "" END AS MENSAJE_QUINTIL,

--PROPENSION FUGA
CASE
WHEN QUINTIL_PROPENSION = 'ALTA' then PUNTAJE_MODELO_FUGA_ALERTA
WHEN QUINTIL_PROPENSION = '1' THEN PUNTAJE_MODELO_FUGA_Q1 
ELSE 0 END AS PUNTAJE_PROPENSION_FUGA, 

CASE
WHEN QUINTIL_PROPENSION = 'ALTA' then MENSAJE_MODELO_FUGA_ALERTA
WHEN QUINTIL_PROPENSION = '1' THEN MENSAJE_MODELO_FUGA_Q1 
ELSE "" END AS MENSAJE_PROPENSION_FUGA, 

from variables_totales),


-- Creacion de Campo para mensajes criticos con saltos de linea
MENSAJE_TOTAL AS (
SELECT RUTEMPRESA,TRIM(STRING_AGG(CONCAT(MENSAJE, '\n'), '' ORDER BY PUNTAJE DESC)) as MENSAJE_TOTAL
FROM (
SELECT RUTEMPRESA,PUNTAJE_EEVV AS PUNTAJE,MENSAJE_EEVV AS MENSAJE,
FROM Puntaje_y_mensaje
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_COBERTURA_TOTAL_U3M,MENSAJE_COBERTURA_TOTAL_U3M
FROM Puntaje_y_mensaje 
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_BLOQUEO_EMPRESA,MENSAJE_BLOQUEO_EMPRESA
FROM Puntaje_y_mensaje 
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_PORC_LEJANOS,MENSAJE_PORC_LEJANOS
FROM Puntaje_y_mensaje 
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_EPA_RECOMENDACION,MENSAJE_EPA_RECOMENDACION
FROM Puntaje_y_mensaje
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_EPA_SATISFACCION,MENSAJE_EPA_SATISFACCION
FROM Puntaje_y_mensaje
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_CANTIDAD_CONTACTOS,MENSAJE_CANTIDAD_CONTACTOS,
FROM Puntaje_y_mensaje
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_QUINTIL,MENSAJE_QUINTIL,
FROM Puntaje_y_mensaje
UNION ALL
SELECT RUTEMPRESA,PUNTAJE_PROPENSION_FUGA,MENSAJE_PROPENSION_FUGA,
FROM Puntaje_y_mensaje)
GROUP BY RUTEMPRESA),


--Incorporacion de campo de mensaje con saltos de linea + calculo de puntaje total
TOTALES AS (
select b.MENSAJE_TOTAL,
(PUNTAJE_EEVV+PUNTAJE_COBERTURA_TOTAL_U3M+PUNTAJE_BLOQUEO_EMPRESA+PUNTAJE_EPA_SATISFACCION+PUNTAJE_EPA_RECOMENDACION+
PUNTAJE_CANTIDAD_CONTACTOS+puntaje_Propension_fuga+PUNTAJE_PORC_LEJANOS+PUNTAJE_QUINTIL) AS PUNTAJE_TOTAL,
TRIM(CONCAT(CONCAT("Ultima Visita: ",Fecha_Ultima_Visita, '\n'),CONCAT("Tipo Visita: ",Tipo_Actividad_Ultima_Visita, '\n'))) as Resumen_Visitas,
TRIM(CONCAT(CONCAT("Empresa: ",N_TRABAJADORES_EMPRESA, '\n'),CONCAT("Holding: ",N_TRABAJADORES_RUT_FINAL, '\n'))) as Resumen_Trabajadores,
a.*
from Puntaje_y_mensaje as a
left join MENSAJE_TOTAL as b
on a.RUTEMPRESA = b.RUTEMPRESA),

-- Segmentacion y Enumeracion de criticidad segun cartera de ejecutivo
FINAL_ANTES_CREACION_KPI_USO AS ( 
SELECT 
case when PUNTAJE_TOTAL>=30 then '1° Orden Gestión' 
when PUNTAJE_TOTAL between 20 and 29 then '2° Orden Gestión' 
when PUNTAJE_TOTAL between 0 and 19 then '3° Orden Gestión' 
else 'Revisar' end as Orden_Gestion,

ROW_NUMBER() OVER (PARTITION BY EJECUTIVO_EMPRESA
ORDER BY 
PUNTAJE_TOTAL DESC,
PUNTAJE_EEVV DESC, 
PUNTAJE_COBERTURA_TOTAL_U3M DESC, 
puntaje_Propension_fuga DESC,
PUNTAJE_QUINTIL DESC,
PUNTAJE_BLOQUEO_EMPRESA DESC,
PUNTAJE_EPA_SATISFACCION DESC,
PUNTAJE_EPA_RECOMENDACION DESC,
PUNTAJE_CANTIDAD_CONTACTOS DESC) AS Ranking_Ejecutivo,*
FROM TOTALES),

--Ranking para stock de productos financieros segun cartera de ejecutivos
KPI_PPFF as (
SELECT *,
ROW_NUMBER() OVER (PARTITION BY EJECUTIVO_EMPRESA
ORDER BY Delta_PPFF) AS Ranking_PPFF_Ejecutivo
FROM (select RUTEMPRESA,STOCK_PPFF_RUT_FINAL-STOCK_PPFF_SEGMENTO_RUT_FINAL as Delta_PPFF,EJECUTIVO_EMPRESA
from TABLA_MAESTRO_EMPRESAS
where STOCK_PPFF_RUT_FINAL is not null
and N_TRABAJADORES_EMPRESA > 20)),

--Ranking de penetracion de beneficios segun cartera de ejecutivos
KPI_BBSS as (
SELECT *,
ROW_NUMBER() OVER (PARTITION BY EJECUTIVO_EMPRESA
ORDER BY Delta_BBSS) AS Ranking_BBSS_Ejecutivo
FROM (select RUTEMPRESA,PENETRACION_BBSS_RUT_FINAL-PENETRACION_BBSS_SEGMENTO_RUT_FINAL as Delta_BBSS,EJECUTIVO_EMPRESA
from TABLA_MAESTRO_EMPRESAS
where PENETRACION_BBSS_RUT_FINAL is not null
and N_TRABAJADORES_EMPRESA > 20)),

--Ranking de penetracion de canales digitales segun cartera de ejecutivos
KPI_CANALES_DIGITALES as (
SELECT *,
ROW_NUMBER() OVER (PARTITION BY EJECUTIVO_EMPRESA
ORDER BY Delta_CANALES) AS Ranking_CANALES_DIGITALES_Ejecutivo
FROM (select RUTEMPRESA,PENETRACION_CANALES_DIGITALES_RUT_FINAL-PENETRACION_CANALES_DIGITALES_SEGMENTO_RUT_FINAL as Delta_CANALES,EJECUTIVO_EMPRESA
from TABLA_MAESTRO_EMPRESAS
where PENETRACION_CANALES_DIGITALES_RUT_FINAL is not null
and N_TRABAJADORES_EMPRESA > 20))

--Incorporacion de rankig de productos, beneficios y uso canales digitales
SELECT a.*,
B.Ranking_PPFF_Ejecutivo,
C.Ranking_BBSS_Ejecutivo,
D.Ranking_CANALES_DIGITALES_Ejecutivo
FROM FINAL_ANTES_CREACION_KPI_USO AS A    

LEFT JOIN KPI_PPFF AS B   
ON A.RUTEMPRESA = B.RutEmpresa

LEFT JOIN KPI_BBSS AS C 
ON A.RUTEMPRESA = C.RutEmpresa

LEFT JOIN KPI_CANALES_DIGITALES AS D
ON A.RUTEMPRESA = D.RutEmpresa